### ISSUE TITLE
关于安装教程

### ISSUE THREAD

**Issue by qsbaq** [btlike/crawl#1]
作者您好，我写了一个安装教程，但是后面的不会安装了，最后几步
env GOPATH=/wwwroot/www.jiloc.com/ go get github.com/btlike/crawl
慢的一笔，几个小时都完成不了，求解！！！

我的安装教程：
http://www.jiloc.com/42480.html

**Comment by bjdudu** [comment]
应该是GIT的版本的问题，git版本要大于1.7，否则访问gopkg.in会卡住
